/* eslint-disable */
/* global WebImporter */


import { applyAnalytics } from './utils/analytics.js';
/**
 * Parser: hero (profile)
 * Base block: hero
 * Variant: profile
 * Source: https://www.abbvie.com/science/our-people/our-rd-leaders/andrew-campbell.html
 * Generated: 2026-03-03
 *
 * Profile hero has no background image — just a navy band (#071D49)
 * followed by a white overlap card with person name and role/title.
 *
 * Library structure: 1 column, 2 rows
 *   Row 1: Empty (CSS provides navy background via .hero.profile)
 *   Row 2: Richtext — H1 person name + P subtitle (field:text)
 *
 * Breadcrumbs are auto-generated by hero.js — not imported.
 *
 * UE Model fields: image (reference, left empty), imageAlt (collapsed), text (richtext)
 */
export default function parse(element, { document }) {
  // Extract text content from the overlap-predecessor container
  const heading = element.querySelector('.cmp-title h1, h1, .cmp-title h2, h2');
  const subtitle = element.querySelector('.cmp-text p, .cmp-text');

  // Build cells: Row 1 = empty (no image), Row 2 = text
  const cells = [];

  // Row 1: Empty image placeholder (CSS provides navy background)
  const imgFrag = document.createDocumentFragment();
  imgFrag.appendChild(document.createComment(' field:image '));
  cells.push([imgFrag]);

  // Row 2: Text content — person name and role
  const textFrag = document.createDocumentFragment();
  textFrag.appendChild(document.createComment(' field:text '));
  if (heading) textFrag.appendChild(heading);
  if (subtitle) textFrag.appendChild(subtitle);
  cells.push([textFrag]);

  const block = WebImporter.Blocks.createBlock(document, { name: 'Hero (profile)', cells });

  // Rule 4: Carry analytics from source to block
  applyAnalytics(element, block, document);

  // Remove the previous sibling (navy background container) since CSS handles it
  const prevSibling = element.previousElementSibling;
  if (prevSibling && prevSibling.querySelector('[style*="background-color"]')) {
    prevSibling.remove();
  }

  element.replaceWith(block);
}
